services:
  app:
    image: ghcr.io/maplumex/videonote:latest
    env_file: .env
    environment:
      - UPLOAD_DIR=/data/videonote
      - FRONTEND_STATIC_DIR=/app/static
    volumes:
      - videonote-data:/data/videonote
    ports:
      - "8965:8000"
    restart: unless-stopped

volumes:
  videonote-data: